number_of_fpgas: 5
number_of_motors: 13
path_planning_pose: 3
live_tracking: 0
controller: 3
max_force: 500
min_force: 50
qp_print_level: 0
qp_working_sets: 1000
planner: "KPIECEkConfigDefault"
planning_group: "lower_arm_left"
log: 0
end_effectors: ["lower_arm_left"]
lower_arm_left:
  Kp: 100
  Kd: 10
  target_pos: [0,0,0,0]
  target_vel: [0,0,0,0]
  
motor0:
  id: 0
  joint_name: motor0
  type: roboy_controller/MuscController

motor1:
  id: 1
  joint_name: motor1
  type: roboy_controller/MuscController

motor2:
  id: 2
  joint_name: motor2
  type: roboy_controller/MuscController

motor3:
  id: 3
  joint_name: motor3
  type: roboy_controller/MuscController

motor4:
  id: 4
  joint_name: motor4
  type: roboy_controller/MuscController

motor5:
  id: 5
  joint_name: motor5
  type: roboy_controller/MuscController

motor6:
  id: 6
  joint_name: motor6
  type: roboy_controller/MuscController

motor7:
  id: 7
  joint_name: motor7
  type: roboy_controller/MuscController

motor8:
  id: 8
  joint_name: motor8
  type: roboy_controller/MuscController

motor9:
  id: 9
  joint_name: motor9
  type: roboy_controller/MuscController

motor10:
  id: 10
  joint_name: motor10
  type: roboy_controller/MuscController

motor11:
  id: 11
  joint_name: motor11
  type: roboy_controller/MuscController

motor12:
  id: 12
  joint_name: motor12
  type: roboy_controller/MuscController

motor13:
  id: 13
  joint_name: motor13
  type: roboy_controller/MuscController

motor14:
  id: 14
  joint_name: motor14
  type: roboy_controller/MuscController

motor15:
  id: 15
  joint_name: motor15
  type: roboy_controller/MuscController

motor16:
  id: 16
  joint_name: motor16
  type: roboy_controller/MuscController

motor17:
  id: 17
  joint_name: motor17
  type: roboy_controller/MuscController

motor18:
  id: 18
  joint_name: motor18
  type: roboy_controller/MuscController

motor19:
  id: 19
  joint_name: motor19
  type: roboy_controller/MuscController

motor20:
  id: 20
  joint_name: motor20
  type: roboy_controller/MuscController

motor21:
  id: 21
  joint_name: motor21
  type: roboy_controller/MuscController

motor22:
  id: 22
  joint_name: motor22
  type: roboy_controller/MuscController

motor23:
  id: 23
  joint_name: motor23
  type: roboy_controller/MuscController
