number_of_fpgas: 3
number_of_motors: 34
controller: 2
max_force: 10000
min_force: 10
qp_print_level: 0
qp_working_sets: 1000
log: 0
end_effectors:
  ["head","wrist_left_1"]

head:
  ForceControl:
    Kp: 100
    Kd: 10
  TorqueControl:
    Kp: 100
    Kd: 10
  PositionControl:
    Kp: 100
    Kd: 0
  target_frame: "cup_aruco_2"
  target_offset: [0,0,0]
  target_rotation: [0,0,0,1]
  target_pos: [0,0,0,0]
  target_vel: [0,0,0,0]
  kinematic_chain: ["base","head"]
  joint_angle_mask: 0x1
  control: 0
  fpga_id: 0
  number_of_motors: 4

wrist_left_1:
  ForceControl:
    Kp: 100
    Kd: 10
  TorqueControl:
    Kp: 100
    Kd: 10
  PositionControl:
    Kp: 100
    Kd: 0
  target_frame: "cup_aruco_2"
  target_offset: [0,0.05,0.1]
  target_rotation: [0.4864,0.54329,0.47472,-0.49285]
  target_pos: [0,0,0,0,0,0]
  target_vel: [0,0,0,0,0,0]
  kinematic_chain: ["base","wrist_left_1"]
  joint_angle_mask: 0x40
  control: 1
  fpga_id: 3
  number_of_motors: 9

wrist_right_1:
  ForceControl:
    Kp: 100
    Kd: 10
  TorqueControl:
    Kp: 100
    Kd: 10
  PositionControl:
    Kp: 100
    Kd: 0
  target_frame: "wrist_right_1"
  target_offset: [0,0,0]
  target_rotation: [0,0,0,1]
  target_pos: [0,0,0,0,0,0]
  target_vel: [0,0,0,0,0,0]
  kinematic_chain: ["base","wrist_right_1"]
  joint_angle_mask: 0x1
  control: 1
  fpga_id: 4
  number_of_motors: 9

Idle: "Idle"
CheckTargetFrames: "LookAtTarget"
LookAtTarget: "CheckIfHeadTargetReached"
CheckIfHeadTargetReached: "GetTargetPositionsAndRotations"
GetTargetPositionsAndRotations: "InverseKinematicsToTarget"
InverseKinematicsToTarget: "CheckIfTargetReached"
CheckIfTargetReached: "CheckTargetFrames"
TrackRealHardwareToTarget: "CheckTargetFrames"