number_of_fpgas: 5
number_of_motors: 13
live_tracking: 0
controller: 2
max_force: 10000
min_force: 10
qp_print_level: 0
qp_working_sets: 1000
log: 0
end_effectors:
  ["head"]
head:
  Kp: 1
  Kd: 0
  target_pos: [0,0,0]
  target_vel: [0,0,0]
  kinematic_chain: ["torso","head"]
  fpga_id: 0